### ISSUE TITLE
Incremental logging

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#11]
When debugging failing jobs or monitoring the progress of long-running jobs, it is crucial to have access to the log. In most cases, even when delegated through a web service, this will be the STDOUT / STDERR of a command line tool.

Right now, only the job status is defined, i.e. exit status, runtime in ms etc. This data is only available/sensible once the job is finished.

Metadata endpoint (if that is where log data is to be stored) needs an efficient way to store log data incrementally (job can post newest log message without inflating the database) and an efficient way to query it (log messages newer than date X).

**Comment by kba** [comment]
wrong project.

**Comment by cneud** [comment]
I am not certain whether to extend https://ocr-d.github.io/cli#logging in this regard or rather move this to an [implementation](https://github.com/OCR-D/core) issue? 

I'also ping @VolkerHartmann because sooner or later we should formulate some concepts about the `workflow` level.

Application (i.e. MP-)specific debugging should imho be limited as much as possible to debgguing the application locally.

**Comment by kba** [comment]
I think this issue is resolved now:

1) Calling the HTTP endpoint of a service returns the URL of a job.
2) HTTP endpoints wrap CLI
3) Output to STDERR and STDOUT from a CLI is captured in two log files
4) Clients can poll on the log files while the job is still running

It is not true incremental logging since log data is opaque, i.e. client cannot ask for log messages since timestamp or only above a certain level.

Under the condition that the CLI wrapper in 3) flushes log data to files regularly, this still covers the use case of debugging a hanging/long-running process.

We do need to define the mechanics of log files in the specs though.

1) Filenames of STDOUT/STDERR logs (e.g. `stdout.log`/`stderr.log` in the workspace directory by default, overrideable by flag)
2) METS `fileGrp@USE` for log data
3) File IDs in the METS fileGroup

**Comment by VolkerHartmann** [comment]
>  1. Filenames of STDOUT/STDERR logs (e.g. |stdout.log|/|stderr.log| in
 >     the workspace directory by default, overrideable by flag)
This can be done by redirection during call so we don't need any flags:
bash: command 2>stderr.log 1>stdout.log
Maybe we have to document that the binaries should be called like this.

 >  2. METS |fileGrp@USE| for log data
USE = OCR-D-STDOUT and OCR-D-STDERR

 >  3. File IDs in the METS fileGroup
FileID of generated file + '_STDERR' or '_STDOUT'

**Comment by kba** [comment]
> This can be done by redirection during call so we don't need any flags:
> 
> ```
> ocrd-xyz .... 2>stderr.log 1>stdout.log
> ```

Implementation detail: Shells buffer output, so with pure redirection, you can run into a situation where a process hangs but the output buffer is not flushed to disk.

> Maybe we have to document that the binaries should be called like this.

It is, in a way: [CLI#logging](https://ocr-d.github.io/cli#logging). You're right, this should **not** be overrideable by flag, MP should just write to STDOUT/STDERR. 

> FileID of generated file + `_STDERR` or `_STDOUT`

Then it cannot be `${WORKSPACE}/stderr.log` but something file-specific. Wouldn't `GROUPID` make more sense, since that is available at invocation?

```
ocrd-xyz -m file://...
==> ${WORKSPACE}/stdout.log
```
```xml
<mets:fileGrp USE="OCR-D-LOG-STDOUT">
  <mets:file mimetype="text/
</mets:fileGrp>

**Comment by wrznr** [comment]
@VolkerHartmann We had a brief discussion on this issue: While the suggestions of @kba concerning the METS integration are reasonable and point a way to continue, a standardized format for the single logging files is still missing. Do you have any ideas which (standard) logging format we could use or if necessary/desirable, could you come up with a suggestion for our own logging format? This would also help us in preparing the benchmarking facilities.

**Comment by VolkerHartmann** [comment]
LogAnalyzers (e.g.: LogMX, Chainsaw) support many types of pattern layout. Nevertheless, we should agree on one format.
I use a DailyRollingFileAppender to not rewrite the date over and over again.
The standard layout for Log4J looks like this:
TIMESTAMP LEVEL [THREAD] CLASS - MESSAGE
Example:
08:01:40.017 [main] ERROR edu.kit.ocrd.MyTestClass - An error message

More detailed: 
TIMESTAMP LEVEL [THREAD] CLASS (FILE:LINE) - MESSAGE
Example:
08:02:19 [main] INFO  edu.kit.ocrd.MyTestClass (MyTestClass.java:47) - Info message

Minimum:
TIMESTAMP LEVEL CLASS - MESSAGE
08:03:40.017 WARN edu.kit.ocrd.MyTestClass - A warn message

In order to be able to evaluate the performance later, we should define our own category(CLASS).(e.g.: ocrd.log.performance). 
However, this point mainly concerns the workflow.

**Comment by kba** [comment]
I think prescribing anything beyond the most minimal log pattern is futile, so I would be for

```
TIME LEVEL LOGGERNAME - MESSAGE
```

I.e. your last sample. That should be all, that MP need to know (and implement).

But the bigger issue here is: Do we want to have this information in METS and if so how? 

If we keep it in METS, how do we distinguish the logs of different modules that produced different files? My proposal above would make that impossible to distinguish.

Who is responsible for adding this information to the METS?

If it's the responsibility of the workflow engine, how does the logging information relate to provenance information?

Should provenance information (in what format) also be part of METS?

How are executions/jobs identified, will they have a URL to which we can tie both logs and provenance information?

If we run multiple modules in a single workflow and that workflow possibly multiple times on the same work, how will that affect METS file size? Even with just references to log and provenance information files (which are available where for how long?), this can lead to many many file references cluttering the METS. I'm not sure how desirable that is for libaries.

Would perhaps logging and provenance information better placed mostly outside the METS, such as in the serialized workspace/BagIt/OCRD-ZIP?

Back to the origin of the issue: How, exactly, would it work if I started a workflow and wanted to see the progress of a task within that workflow by `tail -f`-like following its log?

**Comment by VolkerHartmann** [comment]
1. log pattern: 
    I agree with this: TIME LEVEL LOGGERNAME - MESSAGE

2. distinguish logs: 
    As each fileGrp can only contain one mimetype we have to introduce an additional prefix for fileGrp: "", "LOG-" (https://ocr-d.github.io/mets#file-group-use-syntax) (e.g.: OCR-D-GT-LOG-...)
    This contains both outputs (stdout, stderr). 
    Naming convention: ID_stdout.txt, ID_stderr.txt
    OOPS: What do we do if multiple IDs are involved to one output? (e.g. analyzing whole document)

3. Responsibility: 
    If the modules write everything to stdout/err it has to be collected by the workflow.
    (multiple IDs as input?)

4. Provenance:
    We have to introduce a new prefix for fileGrp: "", "LOG-", "PROV-" (https://ocr-d.github.io/mets#file-group-use-syntax) (e.g.: OCR-D-GT-PROV-...) (Alternative: LOG-, GT_LOG-, PROV-, GT_PROV-)
   a.) Format: ProvOne (http://vcvcomputing.com/provone/provone.html) (was originally planned), alternatively CWLPROV
   b.) identifying jobs: depends on format. All input and output data, parameters as well as jobs must be described.
   c.) multiple runs: When tested and when determining the most efficient/best workflow, the METS files will become very large, although the data will only be referenced.
       However, only the best workflow will be executed in the libraries, so that only the intermediate results used are in the METS file.
       The intermediate results do not have to be saved, the control of which lies with the libraries. Only the provenance data, with the help of which the workflow can be reproduced, are mandatory.

5. Location of log/prov:
    At least provenance has to be part of METS.
    It is optional for the log files, but then we have to solve the problem of assigning logs to jobs.

6. tail -f:
    First, the workflow must be serialized. Parallel steps are not useful in a sequential output.
    Before calling job print at least the command and start date. (output depends on configuration / log level)
    Serializing stdout/err of the job (output depends on configuration / log level)
    After finishing job print once again command and end date.   (output depends on configuration / log level)

**Comment by wrznr** [comment]
@VolkerHartmann @kba Is this issue resolved via the PR? If not what is still necessary?

**Comment by kba** [comment]
No, the PR only implemented the format.

**Comment by wrznr** [comment]
@VolkerHartmann @kba Pls. add a comment regarding the status of this issue.

**Comment by kba** [comment]
@VolkerHartmann Maybe a white paper/spec draft in docs on logging and provenance? Lest we forget.
